# Use the ultralytics image that includes YOLOv8 and export capabilities
FROM ultralytics/ultralytics:latest-jetson-jetpack4

WORKDIR /app

# Copy models from the repository to the container
COPY ./models /app/models
COPY exporter.py /app/exporter.py
COPY yolov5 /app/yolov5

RUN python3 -m pip install -U pip && python3 -m pip install -r /app/yolov5/requirements.txt

CMD ["python3", "/app/exporter.py"]