# Use the ultralytics image that includes YOLOv8 and export capabilities
FROM ultralytics/ultralytics:latest-jetson-jetpack4

WORKDIR /app

# Copy models from the repository to the container
COPY ./models /app/models
COPY convert_models.py /app/convert_models.py

RUN pip install -U pip && pip install -r yolov5/requirements.txt

CMD ["python3", "/app/convert_models.py"]