# Use the ultralytics image that includes YOLOv8 and export capabilities
FROM ultralytics/ultralytics:latest-jetson-jetpack4

WORKDIR /app

CMD for model in /app/models/*.pt; do \
      model_name=$(basename "$model" .pt); \
      yolo export model="$model" format=engine int8=True device=0; \
      mv "$model_name.engine" /app/models/; \
    done
