services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "2080:2080"
      - "6969:6969"
    cap_add: [net_admin, sys_module]
    devices:
      - "dev/net/tun:/dev/net/tun"
    volumes:
      - ./config.json:/etc/sing-box/config.json
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
